{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"43531","self":"https://eucalyptus.atlassian.net/rest/api/2/issue/43531","key":"EUCA-12388","fields":{"issuetype":{"self":"https://eucalyptus.atlassian.net/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://eucalyptus.atlassian.net/secure/viewavatar?size=xsmall&avatarId=14803&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":14803},"timespent":null,"customfield_13100":null,"project":{"self":"https://eucalyptus.atlassian.net/rest/api/2/project/10000","id":"10000","key":"EUCA","name":"Eucalyptus","avatarUrls":{"48x48":"https://eucalyptus.atlassian.net/secure/projectavatar?pid=10000&avatarId=10011","24x24":"https://eucalyptus.atlassian.net/secure/projectavatar?size=small&pid=10000&avatarId=10011","16x16":"https://eucalyptus.atlassian.net/secure/projectavatar?size=xsmall&pid=10000&avatarId=10011","32x32":"https://eucalyptus.atlassian.net/secure/projectavatar?size=medium&pid=10000&avatarId=10011"}},"customfield_11000":null,"fixVersions":[],"customfield_11001":null,"aggregatetimespent":null,"customfield_10310":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/10209","value":"CentOS 6","id":"10209"}],"resolution":{"self":"https://eucalyptus.atlassian.net/rest/api/2/resolution/2","id":"2","description":"The problem described is an issue which will never be fixed.","name":"Won't Fix"},"customfield_10311":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/11500","value":"Edge","id":"11500"}],"customfield_11401":null,"customfield_11400":null,"customfield_10500":{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/10403","value":"Not Applicable","id":"10403"},"customfield_10104":[],"customfield_10302":null,"customfield_10303":null,"customfield_10105":{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/10101","value":"No","id":"10101"},"customfield_10700":null,"customfield_10304":null,"customfield_10701":null,"customfield_10306":null,"customfield_10702":null,"customfield_10703":null,"resolutiondate":"2016-05-26T16:10:45.512-0500","customfield_10308":null,"customfield_10704":null,"customfield_10705":null,"customfield_10309":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/10204","value":"KVM","id":"10204"}],"workratio":-1,"lastViewed":null,"watches":{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/EUCA-12388/watchers","watchCount":1,"isWatching":false},"created":"2016-05-20T15:53:48.571-0500","customfield_12000":null,"priority":{"self":"https://eucalyptus.atlassian.net/rest/api/2/priority/4","iconUrl":"https://eucalyptus.atlassian.net/images/icons/priorities/minor.svg","name":"Minor","id":"4"},"customfield_12400":null,"customfield_12201":null,"customfield_10300":null,"customfield_10102":null,"customfield_12600":"{}","labels":[],"customfield_10301":null,"customfield_11700":null,"aggregatetimeoriginalestimate":null,"timeestimate":null,"versions":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/version/16401","id":"16401","description":"Eucalyptus 4.2.1","name":"4.2.1","archived":false,"released":true,"releaseDate":"2015-12-07"}],"customfield_11901":null,"issuelinks":[],"assignee":null,"updated":"2016-06-06T16:33:26.329-0500","status":{"self":"https://eucalyptus.atlassian.net/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://eucalyptus.atlassian.net/images/icons/statuses/generic.png","name":"Closed","id":"6","statusCategory":{"self":"https://eucalyptus.atlassian.net/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/component/12700","id":"12700","name":"OSG","description":"Object Storage Gateway"}],"timeoriginalestimate":null,"customfield_13000":null,"description":"Error message handling issue moved here from EUCA-12283.\r\n\r\n_Copying the description from [~hspencer]:_\r\n\r\n*Assessment*\r\n\r\nUsed AWS CLI to upload large object (2.2 G) to OSG. The following error was the result:\r\n{code}\r\n[root@c-31 ~]# aws --endpoint-url http://s3.cloud.qa1.eucalyptus-systems.com:8773/ s3 cp --acl public-read ubuntu-xenial-x86-64-cloudtools-v3.img s3://internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img --profile hspencer-qa\r\nupload failed: ./ubuntu-xenial-x86-64-cloudtools-v3.img to s3://internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img\r\nA server error () occurred when calling the UploadPart operation:\r\n\r\n{code}\r\nCommand with debug flag output can be viewed here - https://gist.github.com/hspencer77/7353ad4c5810b6dae8ab85cce2fd969a.  In the output, the following error can be observed:\r\n{code}\r\n....\r\n2016-05-04 20:22:38,272 - Thread-14 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - \"PUT /internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?partNumber=9&uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP HTTP/1.1\" 500 425\r\n2016-05-04 20:22:38,273 - Thread-14 - botocore.parsers - DEBUG - Response headers: {'date': 'Thu, 05 May 2016 03:22:38 GMT', 'content-length': '425', 'x-amz-request-id': '582117ab-d720-483c-91bf-28418520a1c2', 'content-type': 'application/xml'}\r\n2016-05-04 20:22:38,273 - Thread-14 - botocore.parsers - DEBUG - Response body:\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?><Error xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP&amp;partNumber=9</Resource><RequestId>582117ab-d720-483c-91bf-28418520a1c2</RequestId></Error>\r\n2016-05-04 20:22:38,273 - Thread-14 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x3a48f90>\r\n2016-05-04 20:22:38,274 - Thread-14 - botocore.retryhandler - DEBUG - retry needed: retryable HTTP status code received: 500\r\n2016-05-04 20:22:38,274 - Thread-14 - botocore.retryhandler - DEBUG - Retry needed, action of: 7.85042693548\r\n2016-05-04 20:22:38,274 - Thread-14 - botocore.endpoint - DEBUG - Response received to retry, sleeping for 7.85042693548 seconds\r\n2016-05-04 20:22:38,295 - Thread-7 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - \"PUT /internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?partNumber=2&uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP HTTP/1.1\" 500 425\r\n2016-05-04 20:22:38,295 - Thread-7 - botocore.parsers - DEBUG - Response headers: {'date': 'Thu, 05 May 2016 03:22:38 GMT', 'content-length': '425', 'x-amz-request-id': '45a837c8-a62d-46a6-bfc3-75f813e85946', 'content-type': 'application/xml'}\r\n2016-05-04 20:22:38,295 - Thread-7 - botocore.parsers - DEBUG - Response body:\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?><Error xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP&amp;partNumber=2</Resource><RequestId>45a837c8-a62d-46a6-bfc3-75f813e85946</RequestId></Error>\r\n2016-05-04 20:22:38,296 - Thread-7 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x3a48f90>\r\n2016-05-04 20:22:38,296 - Thread-7 - botocore.retryhandler - DEBUG - retry needed: retryable HTTP status code received: 500\r\n2016-05-04 20:22:38,296 - Thread-7 - botocore.retryhandler - DEBUG - Retry needed, action of: 5.46576542877\r\n2016-05-04 20:22:38,296 - Thread-7 - botocore.endpoint - DEBUG - Response received to retry, sleeping for 5.46576542877 seconds\r\n2016-05-04 20:22:38,346 - Thread-6 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - \"PUT /internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?partNumber=1&uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP HTTP/1.1\" 500 425\r\n2016-05-04 20:22:38,347 - Thread-6 - botocore.parsers - DEBUG - Response headers: {'date': 'Thu, 05 May 2016 03:22:38 GMT', 'content-length': '425', 'x-amz-request-id': '41d452f8-9d4f-4df1-af14-e70a589d5676', 'content-type': 'application/xml'}\r\n2016-05-04 20:22:38,347 - Thread-6 - botocore.parsers - DEBUG - Response body:\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?><Error xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP&amp;partNumber=1</Resource><RequestId>41d452f8-9d4f-4df1-af14-e70a589d5676</RequestId></Error>\r\n2016-05-04 20:22:38,348 - Thread-6 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x3a48f90>\r\n2016-05-04 20:22:38,348 - Thread-6 - botocore.retryhandler - DEBUG - retry needed: retryable HTTP status code received: 500\r\n2016-05-04 20:22:38,348 - Thread-6 - botocore.retryhandler - DEBUG - Reached the maximum number of retry attempts: 5\r\n2016-05-04 20:22:38,348 - Thread-6 - botocore.retryhandler - DEBUG - No retry needed.\r\n2016-05-04 20:22:38,348 - Thread-6 - botocore.hooks - DEBUG - Event after-call.s3.UploadPart: calling handler <function enhance_error_msg at 0x3390938>\r\n2016-05-04 20:22:38,348 - Thread-6 - botocore.hooks - DEBUG - Event after-call.s3.UploadPart: calling handler <awscli.errorhandler.ErrorHandler object at 0x3460910>\r\n2016-05-04 20:22:38,348 - Thread-6 - awscli.errorhandler - DEBUG - HTTP Response Code: 500\r\n2016-05-04 20:22:38,354 - Thread-8 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - \"PUT /internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?partNumber=23&uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP HTTP/1.1\" 500 426\r\n2016-05-04 20:22:38,354 - Thread-8 - botocore.parsers - DEBUG - Response headers: {'date': 'Thu, 05 May 2016 03:22:38 GMT', 'content-length': '426', 'x-amz-request-id': '6eb2dfc8-832c-4c51-a5bb-941f8e958b8b', 'content-type': 'application/xml'}\r\n2016-05-04 20:22:38,354 - Thread-8 - botocore.parsers - DEBUG - Response body:\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?><Error xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP&amp;partNumber=23</Resource><RequestId>6eb2dfc8-832c-4c51-a5bb-941f8e958b8b</RequestId></Error>\r\n2016-05-04 20:22:38,354 - Thread-8 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x3a48f90>\r\n2016-05-04 20:22:38,355 - Thread-8 - botocore.retryhandler - DEBUG - retry needed: retryable HTTP status code received: 500\r\n2016-05-04 20:22:38,355 - Thread-8 - botocore.retryhandler - DEBUG - Retry needed, action of: 0.831188545731\r\n2016-05-04 20:22:38,355 - Thread-8 - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.831188545731 seconds\r\n2016-05-04 20:22:38,355 - Thread-13 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - \"PUT /internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?partNumber=19&uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP HTTP/1.1\" 500 426\r\n2016-05-04 20:22:38,356 - Thread-13 - botocore.parsers - DEBUG - Response headers: {'date': 'Thu, 05 May 2016 03:22:38 GMT', 'content-length': '426', 'x-amz-request-id': '4e5297c0-1267-434c-9372-6e30cb5658ec', 'content-type': 'application/xml'}\r\n2016-05-04 20:22:38,356 - Thread-13 - botocore.parsers - DEBUG - Response body:\r\n<?xml version=\"1.0\" encoding=\"UTF-8\" ?><Error xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img?uploadId=VLRMQF7UFBMLUO8VINAIW1OBSJE5IV0BJOUC9B6UU8ACWFW6QUPSE5JQNRNYFPVP&amp;partNumber=19</Resource><RequestId>4e5297c0-1267-434c-9372-6e30cb5658ec</RequestId></Error>\r\n2016-05-04 20:22:38,356 - Thread-13 - botocore.hooks - DEBUG - Event needs-retry.s3.UploadPart: calling handler <botocore.retryhandler.RetryHandler object at 0x3a48f90>\r\n2016-05-04 20:22:38,356 - Thread-13 - botocore.retryhandler - DEBUG - retry needed: retryable HTTP status code received: 500\r\n2016-05-04 20:22:38,356 - Thread-13 - botocore.retryhandler - DEBUG - Retry needed, action of: 3.92777176283\r\n2016-05-04 20:22:38,356 - Thread-13 - botocore.endpoint - DEBUG - Response received to retry, sleeping for 3.92777176283 seconds\r\n2016-05-04 20:22:38,349 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Error during part upload: A server error () occurred when calling the UploadPart operation:\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python2.6/site-packages/awscli/customizations/s3/tasks.py\", line 241, in __call__\r\n    response_data = self._filename.client.upload_part(**params)\r\n  File \"/usr/lib/python2.6/site-packages/botocore/client.py\", line 228, in _api_call\r\n    return self._make_api_call(operation_name, kwargs)\r\n  File \"/usr/lib/python2.6/site-packages/botocore/client.py\", line 488, in _make_api_call\r\n    model=operation_model, context=request_context\r\n  File \"/usr/lib/python2.6/site-packages/botocore/hooks.py\", line 226, in emit\r\n    return self._emit(event_name, kwargs)\r\n  File \"/usr/lib/python2.6/site-packages/botocore/hooks.py\", line 209, in _emit\r\n    response = handler(**kwargs)\r\n  File \"/usr/lib/python2.6/site-packages/awscli/errorhandler.py\", line 70, in __call__\r\n    http_status_code=http_response.status_code)\r\nServerError: A server error () occurred when calling the UploadPart operation:\r\n2016-05-04 20:22:38,401 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Worker thread invoking task: <awscli.customizations.s3.tasks.UploadPartTask object at 0x7f0bd40221d0>\r\n2016-05-04 20:22:38,401 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message=u'upload failed: ./ubuntu-xenial-x86-64-cloudtools-v3.img to s3://internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img\\nA server error () occurred when calling the UploadPart operation: ', error=True, total_parts=None, warning=None)\r\nupload failed: ./ubuntu-xenial-x86-64-cloudtools-v3.img to s3://internal-emis/images/ubuntu-xenial-x86-64-cloudtools.img\r\nA server error () occurred when calling the UploadPart operation:\r\n2016-05-04 20:22:38,401 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Uploading part 24 for filename: /root/ubuntu-xenial-x86-64-cloudtools-v3.img\r\n2016-05-04 20:22:38,401 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Waiting for upload id.\r\n2016-05-04 20:22:38,401 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - Not uploading part, task has been cancelled.\r\n....\r\n{code}\r\n\r\n*Additional Information*\r\n\r\n* Version of AWS CLI\r\n{code}\r\n[root@c-31 ~]# aws --version\r\naws-cli/1.10.17 Python/2.6.6 Linux/2.6.32-573.22.1.el6.x86_64 botocore/1.4.8\r\n{code}\r\n* Error seen on OSG in {{/var/log/eucalyptus/cloud-tracking.log}} file:\r\n{code}\r\n2016-05-04 20:21:52 ERROR | [855fe278-90e5] Data PUT failure to backend for bucketuuid / objectuuid : 5af6fd44-f356-4abc-b68d-7d836c2a9d35/319f956b-f466-4f30-946a-dc693b8444d9-images/ubuntu-xenial-x86-64-cloudtools.img\r\njava.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.\r\n        at java.util.concurrent.FutureTask.report(FutureTask.java:122)\r\n        at java.util.concurrent.FutureTask.get(FutureTask.java:202)\r\n        at com.eucalyptus.objectstorage.ObjectFactoryImpl.waitForCompletion(ObjectFactoryImpl.java:361)\r\n        at com.eucalyptus.objectstorage.ObjectFactoryImpl.createObjectPart(ObjectFactoryImpl.java:682)\r\n        at com.eucalyptus.objectstorage.ObjectStorageGateway.uploadPart(ObjectStorageGateway.java:2111)\r\n        at sun.reflect.GeneratedMethodAccessor2557.invoke(Unknown Source)\r\n        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n        at java.lang.reflect.Method.invoke(Method.java:606)\r\n        at org.mule.model.resolvers.AbstractEntryPointResolver.invokeMethod(AbstractEntryPointResolver.java:151)\r\n        at org.mule.model.resolvers.ReflectionEntryPointResolver.invoke(ReflectionEntryPointResolver.java:121)\r\n        at org.mule.model.resolvers.DefaultEntryPointResolverSet.invoke(DefaultEntryPointResolverSet.java:39)\r\n        at org.mule.component.DefaultComponentLifecycleAdapter.invoke(DefaultComponentLifecycleAdapter.java:343)\r\n        at org.mule.component.AbstractJavaComponent.invokeComponentInstance(AbstractJavaComponent.java:86)\r\n        at org.mule.component.AbstractJavaComponent.doInvoke(AbstractJavaComponent.java:77)\r\n        at org.mule.component.AbstractComponent.invokeInternal(AbstractComponent.java:126)\r\n        at org.mule.component.AbstractComponent.access$000(AbstractComponent.java:61)\r\n        at org.mule.component.AbstractComponent$1$1.process(AbstractComponent.java:242)\r\n        at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)\r\n        at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)\r\n        at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)\r\n        at org.mule.processor.chain.DefaultMessageProcessorChain.doProcess(DefaultMessageProcessorChain.java:95)\r\n        at org.mule.processor.chain.AbstractMessageProcessorChain.process(AbstractMessageProcessorChain.java:70)\r\n        at org.mule.processor.chain.InterceptingChainLifecycleWrapper.doProcess(InterceptingChainLifecycleWrapper.java:54)\r\n        at org.mule.processor.chain.AbstractMessageProcessorChain.process(AbstractMessageProcessorChain.java:70)\r\n        at org.mule.processor.chain.InterceptingChainLifecycleWrapper.access$001(InterceptingChainLifecycleWrapper.java:26)\r\n        at org.mule.processor.chain.InterceptingChainLifecycleWrapper$1.process(InterceptingChainLifecycleWrapper.java:70)\r\n        at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)\r\n        at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)\r\n        at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)\r\n        at org.mule.processor.chain.InterceptingChainLifecycleWrapper.process(InterceptingChainLifecycleWrapper.java:65)\r\n        at org.mule.component.AbstractComponent.process(AbstractComponent.java:160)\r\n        at org.mule.service.processor.ServiceInternalMessageProcessor.process(ServiceInternalMessageProcessor.java:44)\r\n        at org.mule.execution.ExceptionToMessagingExceptionExecutionInterceptor.execute(ExceptionToMessagingExceptionExecutionInterceptor.java:27)\r\n        at org.mule.execution.MessageProcessorNotificationExecutionInterceptor.execute(MessageProcessorNotificationExecutionInterceptor.java:61)\r\n        at org.mule.execution.MessageProcessorExecutionTemplate.execute(MessageProcessorExecutionTemplate.java:47)\r\n        at org.mule.processor.AbstractInterceptingMessageProcessorBase.processNext(AbstractInterceptingMessageProcessorBase.java:106)\r\n        at org.mule.interceptor.AbstractEnvelopeInterceptor.process(AbstractEnvelopeInterceptor.java:55)\r\n        at org.mule.processor.AsyncInterceptingMessageProcessor.processNextTimed(AsyncInterceptingMessageProcessor.java:122)\r\n        at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:192)\r\n        at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker$1.process(AsyncInterceptingMessageProcessor.java:185)\r\n        at org.mule.execution.ExecuteCallbackInterceptor.execute(ExecuteCallbackInterceptor.java:20)\r\n        at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:34)\r\n        at org.mule.execution.HandleExceptionInterceptor.execute(HandleExceptionInterceptor.java:18)\r\n        at org.mule.execution.BeginAndResolveTransactionInterceptor.execute(BeginAndResolveTransactionInterceptor.java:58)\r\n        at org.mule.execution.ResolvePreviousTransactionInterceptor.execute(ResolvePreviousTransactionInterceptor.java:48)\r\n        at org.mule.execution.SuspendXaTransactionInterceptor.execute(SuspendXaTransactionInterceptor.java:54)\r\n        at org.mule.execution.ValidateTransactionalStateInterceptor.execute(ValidateTransactionalStateInterceptor.java:44)\r\n        at org.mule.execution.IsolateCurrentTransactionInterceptor.execute(IsolateCurrentTransactionInterceptor.java:44)\r\n        at org.mule.execution.ExternalTransactionInterceptor.execute(ExternalTransactionInterceptor.java:52)\r\n        at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:32)\r\n        at org.mule.execution.RethrowExceptionInterceptor.execute(RethrowExceptionInterceptor.java:17)\r\n        at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:113)\r\n        at org.mule.execution.TransactionalErrorHandlingExecutionTemplate.execute(TransactionalErrorHandlingExecutionTemplate.java:34)\r\n        at org.mule.processor.AsyncInterceptingMessageProcessor$AsyncMessageProcessorWorker.doRun(AsyncInterceptingMessageProcessor.java:184)\r\n        at org.mule.work.AbstractMuleEventWork.run(AbstractMuleEventWork.java:43)\r\n        at org.mule.work.WorkerContext.run(WorkerContext.java:311)\r\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\r\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\r\n        at java.lang.Thread.run(Thread.java:744)\r\nCaused by: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.\r\n        at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:2575)\r\n        at com.eucalyptus.objectstorage.providers.s3.S3ProviderClient.uploadPart(S3ProviderClient.java:1123)\r\n        at com.eucalyptus.objectstorage.ObjectFactoryImpl$5.call(ObjectFactoryImpl.java:657)\r\n        at com.eucalyptus.objectstorage.ObjectFactoryImpl$5.call(ObjectFactoryImpl.java:652)\r\n        at java.util.concurrent.FutureTask.run(FutureTask.java:262)\r\n        ... 3 more\r\n{code}\r\n\r\n_Copying from EUCA-12283 where [~hspencer] added a comment - 05/May/16 11:02 AM:_\r\n\r\nI am not sure if this is a case where we extend the error messages from what [AWS provides|http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList].  Maybe we could return to the client the error message seen in the cloud-tracking.log:\r\n{code}\r\nUnable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.\r\n{code}","customfield_13200":null,"customfield_11300":null,"customfield_11500":null,"timetracking":{},"customfield_10005":null,"customfield_10401":null,"customfield_10600":null,"customfield_12900":null,"attachment":[],"aggregatetimeestimate":null,"summary":"Vague \"InternalError\" Message from OSG on multi-part upload errors","creator":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=lincoln.thomas","name":"lincoln.thomas","key":"lincoln.thomas","accountId":"557058:f9364c00-87ee-4948-b657-bb8f8f2030ea","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue"},"displayName":"Lincoln Thomas","active":true,"timeZone":"America/Los_Angeles"},"subtasks":[],"reporter":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=lincoln.thomas","name":"lincoln.thomas","key":"lincoln.thomas","accountId":"557058:f9364c00-87ee-4948-b657-bb8f8f2030ea","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/c21bba9797b880c34a5d772e6db4664f?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dlincoln.thomas%26avatarId%3D17800%26noRedirect%3Dtrue"},"displayName":"Lincoln Thomas","active":true,"timeZone":"America/Los_Angeles"},"aggregateprogress":{"progress":0,"total":0},"customfield_12100":"0|i03rsv:","customfield_10000":"5_*:*_1_*:*_0_*|*_10000_*:*_1_*:*_519416952","customfield_10001":"2016-05-26T16:10:45.519-0500","customfield_10200":null,"customfield_10002":null,"customfield_10003":null,"customfield_10400":null,"customfield_12500":null,"customfield_11600":["dmitrii(dmitrii)","lincoln.thomas(lincoln.thomas)"],"customfield_10116":null,"environment":null,"customfield_10117":null,"customfield_11800":null,"customfield_11802":null,"duedate":null,"customfield_11805":null,"progress":{"progress":0,"total":0},"customfield_11806":null,"votes":{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/EUCA-12388/votes","votes":0,"hasVoted":false},"comment":{"comments":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/43531/comment/103774","id":"103774","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=dmitrii","name":"dmitrii","key":"dmitrii","accountId":"557058:1e0ea807-434b-4b54-967f-1dec4a9ede55","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue"},"displayName":"Dmitrii Calzago","active":false,"timeZone":"America/Los_Angeles"},"body":"Will wait for the underlying issue to be fixed.","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=dmitrii","name":"dmitrii","key":"dmitrii","accountId":"557058:1e0ea807-434b-4b54-967f-1dec4a9ede55","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/efb56b507e22d4fc0d8d5e900e5651d5?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Ddmitrii%26avatarId%3D15900%26noRedirect%3Dtrue"},"displayName":"Dmitrii Calzago","active":false,"timeZone":"America/Los_Angeles"},"created":"2016-05-26T16:10:45.519-0500","updated":"2016-05-26T16:10:45.519-0500"}],"maxResults":1,"total":1,"startAt":0},"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]},"customfield_11808":null}}