{"expand":"renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations","id":"33822","self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822","key":"EUCA-10221","fields":{"issuetype":{"self":"https://eucalyptus.atlassian.net/rest/api/2/issuetype/1","id":"1","description":"A problem which impairs or prevents the functions of the product.","iconUrl":"https://eucalyptus.atlassian.net/secure/viewavatar?size=xsmall&avatarId=14803&avatarType=issuetype","name":"Bug","subtask":false,"avatarId":14803},"timespent":null,"customfield_13100":null,"project":{"self":"https://eucalyptus.atlassian.net/rest/api/2/project/10000","id":"10000","key":"EUCA","name":"Eucalyptus","avatarUrls":{"48x48":"https://eucalyptus.atlassian.net/secure/projectavatar?pid=10000&avatarId=10011","24x24":"https://eucalyptus.atlassian.net/secure/projectavatar?size=small&pid=10000&avatarId=10011","16x16":"https://eucalyptus.atlassian.net/secure/projectavatar?size=xsmall&pid=10000&avatarId=10011","32x32":"https://eucalyptus.atlassian.net/secure/projectavatar?size=medium&pid=10000&avatarId=10011"}},"customfield_11000":null,"customfield_11001":null,"fixVersions":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/version/14301","id":"14301","description":"Eucalyptus 4.1.0","name":"4.1.0","archived":false,"released":true,"releaseDate":"2015-01-29"}],"aggregatetimespent":null,"resolution":{"self":"https://eucalyptus.atlassian.net/rest/api/2/resolution/1","id":"1","description":"A fix for this issue is checked into the tree and tested.","name":"Fixed"},"customfield_10310":null,"customfield_10311":null,"customfield_11401":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"customfield_11400":null,"customfield_10302":null,"customfield_10104":[],"customfield_10500":{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/10403","value":"Not Applicable","id":"10403"},"customfield_10105":null,"customfield_10303":null,"customfield_10700":null,"customfield_10304":null,"customfield_10701":null,"customfield_10306":{"self":"https://eucalyptus.atlassian.net/rest/api/2/customFieldOption/10200","value":"High","id":"10200"},"customfield_10702":null,"customfield_10703":null,"resolutiondate":"2015-01-22T12:34:49.118-0600","customfield_10704":null,"customfield_10308":null,"customfield_10705":null,"customfield_10309":null,"workratio":-1,"lastViewed":null,"watches":{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/EUCA-10221/watchers","watchCount":2,"isWatching":false},"created":"2014-12-08T15:13:02.805-0600","customfield_12000":null,"customfield_12400":null,"priority":{"self":"https://eucalyptus.atlassian.net/rest/api/2/priority/1","iconUrl":"https://eucalyptus.atlassian.net/images/icons/priorities/blocker.svg","name":"Blocker","id":"1"},"customfield_12201":null,"customfield_10300":null,"customfield_10102":null,"customfield_12600":"{repository={count=2, dataType=repository}, json={\"cachedValue\":{\"errors\":[],\"summary\":{\"repository\":{\"overall\":{\"count\":2,\"lastUpdated\":\"2014-12-22T20:06:59.000-0600\",\"dataType\":\"repository\"},\"byInstanceType\":{\"github\":{\"count\":2,\"name\":\"GitHub\"}}}}},\"isStale\":true}}","labels":["Logging"],"customfield_10301":null,"customfield_11700":null,"timeestimate":null,"aggregatetimeoriginalestimate":null,"versions":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/version/12806","id":"12806","description":"Eucalyptus 4.0.0","name":"4.0.0","archived":false,"released":true,"releaseDate":"2014-05-30"}],"customfield_11901":null,"issuelinks":[],"assignee":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"updated":"2015-05-08T17:02:48.783-0500","status":{"self":"https://eucalyptus.atlassian.net/rest/api/2/status/6","description":"The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.","iconUrl":"https://eucalyptus.atlassian.net/images/icons/statuses/generic.png","name":"Closed","id":"6","statusCategory":{"self":"https://eucalyptus.atlassian.net/rest/api/2/statuscategory/3","id":3,"key":"done","colorName":"green","name":"Done"}},"components":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/component/12700","id":"12700","name":"OSG","description":"Object Storage Gateway"}],"timeoriginalestimate":null,"customfield_13000":null,"description":"The following error and stack trace were observed during copy object eutester4j tests. Similar errors were also seen when fetching the acl for objects/buckets \r\n{noformat}\r\nTue Nov 25 17:22:18 2014 ERROR [S3AccessControlledEntity:ObjectStorageGateway.09] [com.eucalyptus.objectstorage.entities.S3AccessControlledEntity.getDecodedAcl(S3AccessControlledEntity.java):289] Error decoding acl from DB string\r\njava.lang.ClassCastException: net.sf.json.JSONNull cannot be cast to net.sf.json.JSONObject\r\n        at com.eucalyptus.objectstorage.entities.S3AccessControlledEntity.getDecodedAcl(S3AccessControlledEntity.java:279)\r\n        at com.eucalyptus.objectstorage.entities.S3AccessControlledEntity.can(S3AccessControlledEntity.java:224)\r\n        at com.eucalyptus.objectstorage.auth.OsgAuthorizationHandler.operationAllowed(OsgAuthorizationHandler.java:256)\r\n        at com.eucalyptus.objectstorage.ObjectStorageGateway.copyObject(ObjectStorageGateway.java:1303)\r\n        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n{noformat}","customfield_13200":null,"customfield_11300":null,"customfield_11500":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"timetracking":{},"customfield_10005":null,"customfield_10401":null,"customfield_10600":null,"customfield_12900":null,"attachment":[],"aggregatetimeestimate":null,"summary":"OSG - acl related ops trigger JSON errors in cloud logs ","creator":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"subtasks":[],"reporter":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"customfield_12100":"0|i03053:","aggregateprogress":{"progress":0,"total":0},"customfield_10000":"3_*:*_1_*:*_796079027_*|*_10000_*:*_1_*:*_263620012_*|*_10001_*:*_1_*:*_10782840_*|*_10003_*:*_1_*:*_2808024466_*|*_10006_*:*_1_*:*_0","customfield_10001":"2015-01-15T07:00:57.753-0600","customfield_10200":null,"customfield_10002":null,"customfield_10003":null,"customfield_12500":null,"customfield_10400":null,"customfield_10116":null,"customfield_11600":["shaon(shaon)","swathi(swathi)"],"customfield_10117":null,"environment":null,"customfield_11800":null,"customfield_11802":null,"customfield_11805":null,"duedate":null,"customfield_11806":null,"progress":{"progress":0,"total":0},"votes":{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/EUCA-10221/votes","votes":0,"hasVoted":false},"comment":{"comments":[{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/80796","id":"80796","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"body":"Errors in the logs are caused by incorrect authorization checks in copy object path","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"created":"2014-12-20T22:02:48.380-0600","updated":"2014-12-20T22:02:48.380-0600"},{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/80798","id":"80798","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"body":"Verified using s3curl and eutester4j tests (S3CopyObjectTests and S3ObjectCannedACLTests)","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"created":"2014-12-21T00:34:24.679-0600","updated":"2014-12-21T00:34:24.679-0600"},{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/81891","id":"81891","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"body":"Hey [~swathi],\r\n\r\nLooks like the S3CopyObjectTests is failing completely. I am using the latest commit from eutester testing branch,\r\ncommit 0c83395c8d1526633392ec17b1a1c33e3f16300d\r\n\r\n{noformat}\r\n   [testng] [2015-01-15 04:53:14,071] - *** PRE SUITE SETUP ***\r\n   [testng] [2015-01-15 04:53:14,072] - Getting cloud information from eucarc\r\n   [testng] [2015-01-15 04:53:14,076] - Updating endpoints file\r\n   [testng] [2015-01-15 04:53:14,830] - Created account: s3copyobjecttestsa\r\n   [testng] [2015-01-15 04:53:14,907] - Created new access key for user admin\r\n   [testng] [2015-01-15 04:53:15,105] - Created account: s3copyobjecttestsb\r\n   [testng] [2015-01-15 04:53:15,164] - Created new access key for user admin\r\n   [testng] [2015-01-15 04:53:15,430] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:53:15,430] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:53:15,430] - *****TEST NAME: S3CopyObjectTests - accessDeniedCheck\r\n   [testng] [2015-01-15 04:53:15,430] - s3copyobjecttestsa: Creating bucket 3fcc8d3f9f2d79b0 with canned ACL private\r\n   [testng] [2015-01-15 04:53:17,689] - s3copyobjecttestsa: Putting object with key=3fce6dcb730db828, bucket=3fcc8d3f9f2d79b0, canned ACL=public-read\r\n   [testng] [2015-01-15 04:53:19,871] - s3copyobjecttestsa: Creating bucket 3fd46e5c36316b14 with canned ACL log-delivery-write\r\n   [testng] [2015-01-15 04:53:22,201] - s3copyobjecttestsb: Copying object with source key=3fce6dcb730db828, source bucket=3fcc8d3f9f2d79b0, destination key=3feab430a8f0aa24, destination bucket=3fd46e5c36316b14\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9033b4f3-da59-46d5-88aa-60d5e4f893de), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.accessDeniedCheck(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] [2015-01-15 04:53:22,399] - Caught Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9033b4f3-da59-46d5-88aa-60d5e4f893de)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] [2015-01-15 04:53:22,399] - HTTP Status Code: 403\r\n   [testng] [2015-01-15 04:53:22,399] - Amazon Error Code: AccessDenied\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:53:22,400] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:53:22,400] - s3copyobjecttestsa: Deleting bucket 3fd46e5c36316b14\r\n   [testng] [2015-01-15 04:53:22,776] - s3copyobjecttestsa: Deleting object 3fce6dcb730db828 from bucket 3fcc8d3f9f2d79b0\r\n   [testng] [2015-01-15 04:53:22,975] - s3copyobjecttestsa: Deleting bucket 3fcc8d3f9f2d79b0\r\n   [testng] [2015-01-15 04:53:23,485] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:53:23,485] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:53:23,486] - *****TEST NAME: S3CopyObjectTests - etagConstraint\r\n   [testng] [2015-01-15 04:53:23,486] - s3copyobjecttestsa: Creating bucket 3fea5294ad5801ab with canned ACL private\r\n   [testng] [2015-01-15 04:53:25,741] - s3copyobjecttestsa: Putting object with key=3fccd892d193f348, bucket=3fea5294ad5801ab, canned ACL=private\r\n   [testng] [2015-01-15 04:53:28,015] - s3copyobjecttestsa: Copying object with source key=3fccd892d193f348, source bucket=3fea5294ad5801ab, destination key=3fd6a432c0dc75e6, destination bucket=3fea5294ad5801ab, matching etag constraint=[ad60831f4e29b5dacfe1c68785c101e6]\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 6c19bb93-9a85-4444-8be8-067025d99670), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.etagConstraint(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] [2015-01-15 04:53:31,102] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 6c19bb93-9a85-4444-8be8-067025d99670)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] [2015-01-15 04:53:31,102] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:53:31,102] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:53:31,103] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:53:31,103] - s3copyobjecttestsa: Deleting object 3fccd892d193f348 from bucket 3fea5294ad5801ab\r\n   [testng] [2015-01-15 04:53:31,321] - s3copyobjecttestsa: Deleting bucket 3fea5294ad5801ab\r\n   [testng] [2015-01-15 04:53:31,726] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:53:31,726] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:53:31,726] - *****TEST NAME: S3CopyObjectTests - lastModifiedConstraint\r\n   [testng] [2015-01-15 04:53:31,726] - s3copyobjecttestsb: Creating bucket 3fd492794d81007c with canned ACL private\r\n   [testng] [2015-01-15 04:53:33,987] - s3copyobjecttestsb: Putting object with key=3fc9870581220efc, bucket=3fd492794d81007c, canned ACL=private\r\n   [testng] [2015-01-15 04:53:36,195] - s3copyobjecttestsb: Copying object with source key=3fc9870581220efc, source bucket=3fd492794d81007c, destination key=3fd7b3dd550b4792, destination bucket=3fd492794d81007c, modified since constraint=Thu Jan 15 02:06:51 PST 2015\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 4c51cfae-e5a7-4aa1-a9da-c71e53930dfa), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.lastModifiedConstraint(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] [2015-01-15 04:53:39,078] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 4c51cfae-e5a7-4aa1-a9da-c71e53930dfa)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] [2015-01-15 04:53:39,078] - HTTP Status Code: 500\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] [2015-01-15 04:53:39,078] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:53:39,079] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:53:39,079] - s3copyobjecttestsb: Deleting object 3fc9870581220efc from bucket 3fd492794d81007c\r\n   [testng] [2015-01-15 04:53:39,243] - s3copyobjecttestsb: Deleting bucket 3fd492794d81007c\r\n   [testng] [2015-01-15 04:53:39,692] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:53:39,692] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:53:39,692] - *****TEST NAME: S3CopyObjectTests - metadataDirective\r\n   [testng] [2015-01-15 04:53:39,692] - s3copyobjecttestsa: Creating bucket 3fd9988574fbca2a with canned ACL private\r\n   [testng] [2015-01-15 04:53:41,892] - s3copyobjecttestsa: Putting object with key=3fe49c4e1b37b810, bucket=3fd9988574fbca2a, canned ACL=private, user metadata={hello=world, somerandomkey=somerandomvalue}\r\n   [testng] [2015-01-15 04:53:44,099] - s3copyobjecttestsa: Copying object with source key=3fe49c4e1b37b810, source bucket=3fd9988574fbca2a, destination key=3fe1ff1b219ad0c1, destination bucket=3fd9988574fbca2a\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 9e98b743-fed1-4736-b3a8-9ba96dfbc987), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.metadataDirective(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] [2015-01-15 04:53:46,815] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 9e98b743-fed1-4736-b3a8-9ba96dfbc987)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:53:46,815] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:53:46,815] - Amazon Error Code: InternalError\r\n   [testng] [2015-01-15 04:53:46,816] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:53:46,816] - s3copyobjecttestsa: Deleting object 3fe49c4e1b37b810 from bucket 3fd9988574fbca2a\r\n   [testng] [2015-01-15 04:53:46,964] - s3copyobjecttestsa: Deleting bucket 3fd9988574fbca2a\r\n   [testng] [2015-01-15 04:53:47,294] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:53:47,294] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:53:47,294] - *****TEST NAME: S3CopyObjectTests - metadataDirective_SameObject\r\n   [testng] [2015-01-15 04:53:47,294] - s3copyobjecttestsb: Creating bucket 3fe00b83989484ed with canned ACL private\r\n   [testng] [2015-01-15 04:53:49,489] - s3copyobjecttestsb: Putting object with key=3fd5e5c3ff4fa486, bucket=3fe00b83989484ed, canned ACL=private, user metadata={hello=world, somerandomkey=somerandomvalue}\r\n   [testng] [2015-01-15 04:53:51,654] - s3copyobjecttestsb: Copying object with source key=3fd5e5c3ff4fa486, source bucket=3fe00b83989484ed, destination key=3fd5e5c3ff4fa486, destination bucket=3fe00b83989484ed\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: b68be56d-a4f3-489b-9f84-541ae8f858ea), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.metadataDirective_SameObject(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] [2015-01-15 04:53:54,379] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: b68be56d-a4f3-489b-9f84-541ae8f858ea)\r\n   [testng] [2015-01-15 04:53:54,379] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:53:54,379] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:53:54,380] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:53:54,380] - s3copyobjecttestsb: Deleting object 3fd5e5c3ff4fa486 from bucket 3fe00b83989484ed\r\n   [testng] [2015-01-15 04:53:54,535] - s3copyobjecttestsb: Deleting bucket 3fe00b83989484ed\r\n   [testng] [2015-01-15 04:53:54,820] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:53:54,820] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:53:54,821] - *****TEST NAME: S3CopyObjectTests - multipleUsersDifferentBuckets1\r\n   [testng] [2015-01-15 04:53:54,821] - s3copyobjecttestsa: Creating bucket 3fc75eca7ea11e78 with canned ACL private\r\n   [testng] [2015-01-15 04:53:57,017] - s3copyobjecttestsa: Putting object with key=3fd24e48582c9374, bucket=3fc75eca7ea11e78, canned ACL=authenticated-read\r\n   [testng] [2015-01-15 04:53:59,182] - s3copyobjecttestsb: Creating bucket 3fda74fedfbe725e with canned ACL private\r\n   [testng] [2015-01-15 04:54:01,365] - s3copyobjecttestsb: Copying object with source key=3fd24e48582c9374, source bucket=3fc75eca7ea11e78, destination key=3fc9de0272f27748, destination bucket=3fda74fedfbe725e\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 4e857268-79fb-400f-bdd3-4726291ae99c), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.multipleUsersDifferentBuckets1(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] [2015-01-15 04:54:04,039] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 4e857268-79fb-400f-bdd3-4726291ae99c)\r\n   [testng] [2015-01-15 04:54:04,039] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:54:04,039] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:04,039] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:54:04,039] - s3copyobjecttestsb: Deleting bucket 3fda74fedfbe725e\r\n   [testng] [2015-01-15 04:54:04,204] - s3copyobjecttestsa: Deleting object 3fd24e48582c9374 from bucket 3fc75eca7ea11e78\r\n   [testng] [2015-01-15 04:54:04,347] - s3copyobjecttestsa: Deleting bucket 3fc75eca7ea11e78\r\n   [testng] [2015-01-15 04:54:04,640] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:54:04,640] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:54:04,640] - *****TEST NAME: S3CopyObjectTests - multipleUsersDifferentBuckets2\r\n   [testng] [2015-01-15 04:54:04,640] - s3copyobjecttestsa: Creating bucket 3fd9d61ed5ab3e86 with canned ACL private\r\n   [testng] [2015-01-15 04:54:06,829] - s3copyobjecttestsa: Putting object with key=3fe824a3452103ed, bucket=3fd9d61ed5ab3e86, canned ACL=authenticated-read\r\n   [testng] [2015-01-15 04:54:08,977] - s3copyobjecttestsa: Creating bucket 3fda1b0dde02d6be with canned ACL public-read-write\r\n   [testng] [2015-01-15 04:54:11,160] - s3copyobjecttestsb: Copying object with source key=3fe824a3452103ed, source bucket=3fd9d61ed5ab3e86, destination key=3fbf392fca867d00, destination bucket=3fda1b0dde02d6be\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 1ba8342e-8211-4387-9b9d-2c6304f88550), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.multipleUsersDifferentBuckets2(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] [2015-01-15 04:54:13,835] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 1ba8342e-8211-4387-9b9d-2c6304f88550)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] [2015-01-15 04:54:13,835] - HTTP Status Code: 500\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] [2015-01-15 04:54:13,835] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] [2015-01-15 04:54:13,835] - *** POST TEST CLEANUP ***\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:13,835] - s3copyobjecttestsa: Deleting bucket 3fda1b0dde02d6be\r\n   [testng] [2015-01-15 04:54:14,011] - s3copyobjecttestsa: Deleting object 3fe824a3452103ed from bucket 3fd9d61ed5ab3e86\r\n   [testng] [2015-01-15 04:54:14,159] - s3copyobjecttestsa: Deleting bucket 3fd9d61ed5ab3e86\r\n   [testng] [2015-01-15 04:54:14,452] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:54:14,452] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:54:14,452] - *****TEST NAME: S3CopyObjectTests - multipleUsersSameBucket\r\n   [testng] [2015-01-15 04:54:14,452] - s3copyobjecttestsa: Creating bucket 3fd24f5c96111db6 with canned ACL public-read-write\r\n   [testng] [2015-01-15 04:54:16,649] - s3copyobjecttestsa: Putting object with key=3fd35889e6b8592e, bucket=3fd24f5c96111db6, canned ACL=authenticated-read\r\n   [testng] [2015-01-15 04:54:18,832] - s3copyobjecttestsb: Copying object with source key=3fd35889e6b8592e, source bucket=3fd24f5c96111db6, destination key=3fe50491956f6b8d, destination bucket=3fd24f5c96111db6\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: d2c06668-f5ca-46a1-941f-ab123d324f75), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.multipleUsersSameBucket(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] [2015-01-15 04:54:21,506] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: d2c06668-f5ca-46a1-941f-ab123d324f75)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:21,506] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:54:21,506] - Amazon Error Code: InternalError\r\n   [testng] [2015-01-15 04:54:21,507] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:54:21,507] - s3copyobjecttestsa: Deleting object 3fd35889e6b8592e from bucket 3fd24f5c96111db6\r\n   [testng] [2015-01-15 04:54:21,649] - s3copyobjecttestsa: Deleting bucket 3fd24f5c96111db6\r\n   [testng] [2015-01-15 04:54:21,941] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:54:21,941] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:54:21,941] - *****TEST NAME: S3CopyObjectTests - nonCannedACLInHeader\r\n   [testng] [2015-01-15 04:54:21,943] - s3copyobjecttestsa: Creating bucket 3fe61cbdbad53819 with canned acl AccessControlList [owner=null, grants=[Grant [grantee=GroupGrantee [http://acs.amazonaws.com/groups/global/AllUsers], permission=READ], Grant [grantee=GroupGrantee [http://acs.amazonaws.com/groups/global/AllUsers], permission=WRITE]]]\r\n   [testng] [2015-01-15 04:54:24,123] - s3copyobjecttestsa: Putting object with key=3fd25728c04a56c4, bucket=3fe61cbdbad53819\r\n   [testng] [2015-01-15 04:54:26,289] - s3copyobjecttestsb: Copying object with source key=3fd25728c04a56c4, source bucket=3fe61cbdbad53819, destination key=3fe22d16fa17a134, destination bucket=3fe61cbdbad53819\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: f1b0892d-c8ce-4925-86da-13077a6dbc92), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.nonCannedACLInHeader(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] [2015-01-15 04:54:28,929] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: f1b0892d-c8ce-4925-86da-13077a6dbc92)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:28,929] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:54:28,929] - Amazon Error Code: InternalError\r\n   [testng] [2015-01-15 04:54:28,930] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:54:28,930] - s3copyobjecttestsa: Deleting object 3fd25728c04a56c4 from bucket 3fe61cbdbad53819\r\n   [testng] [2015-01-15 04:54:29,062] - s3copyobjecttestsa: Deleting bucket 3fe61cbdbad53819\r\n   [testng] [2015-01-15 04:54:29,347] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:54:29,347] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:54:29,347] - *****TEST NAME: S3CopyObjectTests - oneUserDifferentBuckets\r\n   [testng] [2015-01-15 04:54:29,347] - s3copyobjecttestsa: Creating bucket 3fda993ac6a495d8 with canned ACL public-read-write\r\n   [testng] [2015-01-15 04:54:31,537] - s3copyobjecttestsa: Putting object with key=3fee1bf7ec7548bc, bucket=3fda993ac6a495d8, canned ACL=private\r\n   [testng] [2015-01-15 04:54:33,694] - s3copyobjecttestsa: Creating bucket 3fc9aa8c3b491470 with canned ACL private\r\n   [testng] [2015-01-15 04:54:35,894] - s3copyobjecttestsa: Copying object with source key=3fee1bf7ec7548bc, source bucket=3fda993ac6a495d8, destination key=3fc15c75b27b310c, destination bucket=3fc9aa8c3b491470\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 4828aa13-1eb8-4571-ab9b-83a7569b20e6), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.oneUserDifferentBuckets(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] [2015-01-15 04:54:38,650] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 4828aa13-1eb8-4571-ab9b-83a7569b20e6)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] [2015-01-15 04:54:38,650] - HTTP Status Code: 500\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] [2015-01-15 04:54:38,650] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] [2015-01-15 04:54:38,651] - *** POST TEST CLEANUP ***\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] [2015-01-15 04:54:38,651] - s3copyobjecttestsa: Deleting bucket 3fc9aa8c3b491470\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:38,807] - s3copyobjecttestsa: Deleting object 3fee1bf7ec7548bc from bucket 3fda993ac6a495d8\r\n   [testng] [2015-01-15 04:54:38,951] - s3copyobjecttestsa: Deleting bucket 3fda993ac6a495d8\r\n   [testng] [2015-01-15 04:54:39,235] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:54:39,235] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:54:39,236] - *****TEST NAME: S3CopyObjectTests - oneUserSameBucket\r\n   [testng] [2015-01-15 04:54:39,236] - s3copyobjecttestsa: Creating bucket 3fd790197c5c206e with canned ACL public-read-write\r\n   [testng] [2015-01-15 04:54:41,425] - s3copyobjecttestsa: Putting object with key=3fe329e38ace791a, bucket=3fd790197c5c206e, canned ACL=private\r\n   [testng] [2015-01-15 04:54:43,599] - s3copyobjecttestsa: Copying object with source key=3fe329e38ace791a, source bucket=3fd790197c5c206e, destination key=3fd69a050447fc6a, destination bucket=3fd790197c5c206e\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e6258bb1-44aa-4ff0-960a-924070e401c7), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.oneUserSameBucket(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] [2015-01-15 04:54:46,290] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: e6258bb1-44aa-4ff0-960a-924070e401c7)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] [2015-01-15 04:54:46,290] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:54:46,290] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] [2015-01-15 04:54:46,291] - *** POST TEST CLEANUP ***\r\n   [testng] [2015-01-15 04:54:46,291] - s3copyobjecttestsa: Deleting object 3fe329e38ace791a from bucket 3fd790197c5c206e\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:46,448] - s3copyobjecttestsa: Deleting bucket 3fd790197c5c206e\r\n   [testng] [2015-01-15 04:54:46,729] - *** PRE TEST SETUP ***\r\n   [testng] [2015-01-15 04:54:46,729] - Initializing bucket name, key name and clean up tasks\r\n   [testng] [2015-01-15 04:54:46,729] - *****TEST NAME: S3CopyObjectTests - versionedBuckets\r\n   [testng] [2015-01-15 04:54:46,736] - s3copyobjecttestsa: Creating bucket 3fe1c1422492d68b with canned ACL private\r\n   [testng] [2015-01-15 04:54:48,929] - s3copyobjecttestsa: Enabling versioning for bucket 3fe1c1422492d68b\r\n   [testng] [2015-01-15 04:54:51,053] - s3copyobjecttestsa: Putting object with key=3fe176edfb4c9497, bucket=3fe1c1422492d68b, canned ACL=private\r\n   [testng] [2015-01-15 04:54:53,245] - s3copyobjecttestsa: Putting object with key=3fe176edfb4c9497, bucket=3fe1c1422492d68b, canned ACL=private\r\n   [testng] [2015-01-15 04:54:55,420] - s3copyobjecttestsa: Copying object with source key=3fe176edfb4c9497, source bucket=3fe1c1422492d68b, destination key=3fe36082b3e5c85f, destination bucket=3fe1c1422492d68b, canned ACL=log-delivery-write, version ID=94ec876e2e0e4050a37109dd57da0e29\r\n   [testng] com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 51b12000-7a47-4952-be42-309aa29c2f6b), S3 Extended Request ID: null\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)\r\n   [testng] \tat com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)\r\n   [testng] \tat com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1551)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.copyObject(Unknown Source)\r\n   [testng] \tat com.eucalyptus.tests.awssdk.S3CopyObjectTests.versionedBuckets(Unknown Source)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n   [testng] \tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\r\n   [testng] \tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n   [testng] \tat java.lang.reflect.Method.invoke(Method.java:606)\r\n   [testng] \tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n   [testng] \tat org.testng.internal.Invoker.invokeMethod(Invoker.java:714)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)\r\n   [testng] \tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n   [testng] \tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n   [testng] \tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n   [testng] [2015-01-15 04:54:58,127] - Caught Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: 51b12000-7a47-4952-be42-309aa29c2f6b)\r\n   [testng] \tat org.testng.TestRunner.run(TestRunner.java:617)\r\n   [testng] \tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n   [testng] [2015-01-15 04:54:58,127] - HTTP Status Code: 500\r\n   [testng] [2015-01-15 04:54:58,127] - Amazon Error Code: InternalError\r\n   [testng] \tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n   [testng] \tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n   [testng] \tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n   [testng] \tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n   [testng] \tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n   [testng] \tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n   [testng] [2015-01-15 04:54:58,128] - *** POST TEST CLEANUP ***\r\n   [testng] \tat org.testng.TestNG.run(TestNG.java:1057)\r\n   [testng] [2015-01-15 04:54:58,128] - s3copyobjecttestsa: Deleting object 3fe176edfb4c9497, version 598b1c5b55504ab69393ffb3ff7590ac from bucket 3fe1c1422492d68b\r\n   [testng] \tat org.testng.TestNG.privateMain(TestNG.java:1364)\r\n   [testng] \tat org.testng.TestNG.main(TestNG.java:1333)\r\n   [testng] [2015-01-15 04:54:58,294] - s3copyobjecttestsa: Deleting object 3fe176edfb4c9497, version 94ec876e2e0e4050a37109dd57da0e29 from bucket 3fe1c1422492d68b\r\n   [testng] [2015-01-15 04:54:58,468] - s3copyobjecttestsa: Deleting bucket 3fe1c1422492d68b\r\n   [testng] [2015-01-15 04:54:58,784] - *** POST SUITE CLEANUP ***\r\n   [testng] [2015-01-15 04:54:58,965] - Deleted account: s3copyobjecttestsa\r\n   [testng] [2015-01-15 04:54:59,100] - Deleted account: s3copyobjecttestsb\r\n   [testng]\r\n   [testng] ===============================================\r\n   [testng] Walrus Test Suite\r\n   [testng] Total tests run: 12, Failures: 11, Skips: 0\r\n{noformat}\r\n","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-15T07:00:57.753-0600","updated":"2015-01-15T07:00:57.753-0600"},{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/81909","id":"81909","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"body":"[~shaon], can you send me the cloud logs or email me the details to this cloud setup? ","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-15T11:44:01.892-0600","updated":"2015-01-15T11:44:01.892-0600"},{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/81912","id":"81912","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"body":"[~shaon], I just ran S3CopyObjectTests against the latest from eucalyptus testing branch and all tests passed. ","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=swathi","name":"swathi","key":"swathi","accountId":"557058:ab7e71b5-781c-49ea-9f4d-ea9148c88f03","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/d6487612d6674329ecef11be0a95552b?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dswathi%26avatarId%3D17901%26noRedirect%3Dtrue"},"displayName":"Swathi Gangisetty","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-15T12:20:20.571-0600","updated":"2015-01-15T12:20:20.571-0600"},{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/81989","id":"81989","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"body":"Sorry for the false alarm on this one. I was testing against RiakCS backend, which doesn't support copy operation by default.","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-15T23:20:13.784-0600","updated":"2015-01-15T23:20:13.784-0600"},{"self":"https://eucalyptus.atlassian.net/rest/api/2/issue/33822/comment/82425","id":"82425","author":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"body":"Not seeing this in the log anymore.\r\n\r\n{noformat}\r\nName        : eucalyptus                   Relocations: (not relocatable)\r\nVersion     : 4.1.0                             Vendor: Eucalyptus Systems, Inc.\r\nRelease     : 0.0.23040.365.20150121gitd6c7675.el6   Build Date: Wed 21 Jan 2015 02:16:08 PM PST\r\nInstall Date: Thu 22 Jan 2015 12:54:37 AM PST      Build Host: ip-172-16-20-98\r\n{noformat}","updateAuthor":{"self":"https://eucalyptus.atlassian.net/rest/api/2/user?username=shaon","name":"shaon","key":"shaon","accountId":"557058:1e5e1aa5-5986-4a9e-b9ed-814f7000cd4f","avatarUrls":{"48x48":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=48&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3FownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","24x24":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=24&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","16x16":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=16&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dxsmall%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue","32x32":"https://avatar-cdn.atlassian.com/70d1c1681d03ea38518d3b4f59db4385?s=32&d=https%3A%2F%2Feucalyptus.atlassian.net%2Fsecure%2Fuseravatar%3Fsize%3Dmedium%26ownerId%3Dshaon%26avatarId%3D11900%26noRedirect%3Dtrue"},"displayName":"Imran Hossain Shaon","active":true,"timeZone":"America/Los_Angeles"},"created":"2015-01-22T12:34:49.148-0600","updated":"2015-01-22T12:34:49.148-0600"}],"maxResults":7,"total":7,"startAt":0},"customfield_11808":null,"worklog":{"startAt":0,"maxResults":20,"total":0,"worklogs":[]}}}